name: CD

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Deploy mode"
        required: true
        default: "full"
        type: choice
        options:
          - full
          - proxy
          - frontend
          - backend

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (for context only)
        uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            set -eu
            cd "${{ secrets.EC2_WORKDIR }}"
            echo "==> Pulling latest"
            git fetch --all --prune
            git pull --ff-only

            MODE="${{ inputs.mode }}"
            if [ "$MODE" = "full" ]; then
              echo "==> Full rebuild"
              bash deploy/prod.sh --full
            elif [ "$MODE" = "proxy" ]; then
              echo "==> Proxy only"
              bash deploy/prod.sh --proxy
            elif [ "$MODE" = "frontend" ]; then
              echo "==> Frontend rebuild"
              bash deploy/prod.sh --frontend
            elif [ "$MODE" = "backend" ]; then
              echo "==> Backend rebuild + migrate"
              bash deploy/prod.sh --backend --migrate
            fi

            echo "==> Health check"
            bash deploy/prod.sh --health || true

